namespace PocceMod.Shared
{
    public enum Ability
    {
        SpawnVehicle,
        SpawnVehicleByName,
        SpawnProp,
        SpawnPocceCompanion,
        SpawnPetCompanion,
        SpawnPoccePassengers,
        SpawnTrashPed,
        Rope,
        RopeOtherPlayer,
        RopeGun,
        RopeGunStaticObjects,
        RappelFromHeli,
        TeleportToClosestVehicle,
        OceanWaves,
        PocceParty,
        PocceRiot,
        PocceRiotArmed,
        PedRiot,
        PedRiotArmed,
        MassScenario,
        Autopilot,
        EMP,
        EMPOtherPlayer,
        CargobobMagnet,
        UltrabrightHeadlight,
        BackToTheFuture,
        CompressVehicle,
        AntiGravity,
        Balloons,
        IdentifySkins,
        ChangeSkin
    }
}
